USE Library
GO

ALTER PROCEDURE Question7
AS
BEGIN
	SELECT a1.BranchName,a2.Title,a3.Number_Of_Copies
	FROM LIBRARY_BRANCH a1
	INNER JOIN BOOK_COPIES a3 ON a3.BranchID = a1.BranchID
	INNER JOIN BOOKS a2 ON a2.BookID = a3.BookID
	INNER JOIN BOOK_AUTHORS a4 ON a4.BookID = a2.BookID
	WHERE 
	AuthorName = 'Stephen King' AND BranchName = 'Central'
END

SELECT * FROM BOOK_AUTHORS
SELECT * FROM BOOK_COPIES
SELECT * FROM BOOK_LOANS
SELECT * FROM BOOKS
SELECT * FROM BORROWER
SELECT * FROM LIBRARY_BRANCH
SELECT * FROM PUBLISHER